spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
oauth2:
  user:
    google:
      client-id: test-client-id
      client-secret: test-client-secret
      redirect-uri: http://localhost:8080/admin
  provider:
    google:
      token-uri: http://localhost:8888/token
      user-info-uri: http://localhost:8888/user-info
jwt:
  secret-key: test
  expired-time: 86400000